### A MNIST-like fashion product database

In this, we classify the images into respective classes given in the dataset. We use a Neural Net and a Deep Neural Net in Keras to solve this and check the accuracy scores.

### Load tensorflow

In [71]:
import tensorflow as tf
tf.set_random_seed(42)

In [72]:
tf.__version__

'1.12.0'

### Collect Data

In [73]:
import keras as kr

In [74]:
(train_images,train_labels),(test_images,test_labels) = keras.datasets.fashion_mnist.load_data()

In [75]:
print(train_labels[0:5])

[9 0 0 3 0]


In [76]:
print(train_labels.shape)

(60000,)


In [77]:
print(test_labels.shape)

(10000,)


### Convert both training and testing labels into one-hot vectors.

**Hint:** check **tf.keras.utils.to_categorical()**

In [78]:

train_labels = tf.keras.utils.to_categorical(train_labels,num_classes=10)
        
test_labels = tf.keras.utils.to_categorical(test_labels,num_classes=10)

In [79]:
print(train_labels.shape)
print('First 5 examples now are: ', train_labels[0:5])

(60000, 10)
First 5 examples now are:  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Visualize the data

Plot first 10 images in the triaining set and their labels.

In [80]:
trainX=train_images
trainY=train_labels
testX=test_images
testY=test_labels

### Build a neural Network with a cross entropy loss function and sgd optimizer in Keras. The output layer with 10 neurons as we have 10 classes.

In [81]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))



#Add Dense Layer which provides 10 Outputs after applying softmax
model.add(tf.keras.layers.Dense(10, activation='softmax'))

model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

In [82]:
print(trainX.shape[0])

60000


### Execute the model using model.fit()

In [83]:
model.fit(trainX, trainY, 
          validation_data=(testX, testY), 
          epochs=50,
          batch_size=trainX.shape[0])

Train on 60000 samples, validate on 10000 samples
Epoch 1/50
60000/60000 [==============================] - 1s 23us/step - loss: 12.3277 - acc: 0.2204 - val_loss: 12.4029 - val_acc: 0.2260
Epoch 2/50
60000/60000 [==============================] - 0s 8us/step - loss: 12.3974 - acc: 0.2264 - val_loss: 11.9730 - val_acc: 0.2474
Epoch 3/50
60000/60000 [==============================] - 1s 9us/step - loss: 11.9311 - acc: 0.2498 - val_loss: 11.8669 - val_acc: 0.2626
Epoch 4/50
60000/60000 [==============================] - 0s 8us/step - loss: 11.8867 - acc: 0.2612 - val_loss: 11.7079 - val_acc: 0.2722
Epoch 5/50
60000/60000 [==============================] - 0s 8us/step - loss: 11.7206 - acc: 0.2712 - val_loss: 11.4734 - val_acc: 0.2849
Epoch 6/50
60000/60000 [==============================] - 0s 8us/step - loss: 11.5016 - acc: 0.2834 - val_loss: 11.3488 - val_acc: 0.2912
Epoch 7/50
60000/60000 [==============================] - 0s 8us/step - loss: 11.3391 - acc: 0.2920 - val_loss: 11.2312 -

### In the above Neural Network model add Batch Normalization layer after the input layer and repeat the steps.

In [84]:
trainX=train_images
trainY=train_labels
testX=test_images
testY=test_labels

In [85]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

#Add Dense Layer which provides 10 Outputs after applying softmax
model.add(tf.keras.layers.Dense(10, activation='softmax'))


model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

### Execute the model

In [86]:
model.fit(trainX, trainY, 
          validation_data=(testX, testY), 
          epochs=50,
          batch_size=trainX.shape[0])

Train on 60000 samples, validate on 10000 samples
Epoch 1/50
60000/60000 [==============================] - 2s 26us/step - loss: 2.6315 - acc: 0.1593 - val_loss: 11.1229 - val_acc: 0.1550
Epoch 2/50
60000/60000 [==============================] - 1s 9us/step - loss: 2.4006 - acc: 0.1989 - val_loss: 9.4046 - val_acc: 0.1762
Epoch 3/50
60000/60000 [==============================] - 1s 9us/step - loss: 2.2129 - acc: 0.2392 - val_loss: 8.0101 - val_acc: 0.2055
Epoch 4/50
60000/60000 [==============================] - 1s 8us/step - loss: 2.0586 - acc: 0.2774 - val_loss: 6.9076 - val_acc: 0.2360
Epoch 5/50
60000/60000 [==============================] - 1s 9us/step - loss: 1.9305 - acc: 0.3140 - val_loss: 6.0195 - val_acc: 0.2692
Epoch 6/50
60000/60000 [==============================] - 1s 8us/step - loss: 1.8232 - acc: 0.3486 - val_loss: 5.2817 - val_acc: 0.2988
Epoch 7/50
60000/60000 [==============================] - 1s 9us/step - loss: 1.7324 - acc: 0.3779 - val_loss: 4.6668 - val_acc: 0.3

### Customize the learning rate to 0.001 in sgd optimizer and run the model

In [87]:
sgd_optimizer = tf.keras.optimizers.SGD(lr=0.01)
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(trainX, trainY, 
          validation_data=(testX, testY), 
          epochs=50,
          batch_size=trainX.shape[0])

Train on 60000 samples, validate on 10000 samples
Epoch 1/50
60000/60000 [==============================] - 2s 26us/step - loss: 0.8925 - acc: 0.6999 - val_loss: 1.1069 - val_acc: 0.6573
Epoch 2/50
60000/60000 [==============================] - 1s 9us/step - loss: 0.8875 - acc: 0.7016 - val_loss: 1.0958 - val_acc: 0.6589
Epoch 3/50
60000/60000 [==============================] - 1s 8us/step - loss: 0.8826 - acc: 0.7031 - val_loss: 1.0850 - val_acc: 0.6611
Epoch 4/50
60000/60000 [==============================] - 1s 9us/step - loss: 0.8779 - acc: 0.7048 - val_loss: 1.0745 - val_acc: 0.6635
Epoch 5/50
60000/60000 [==============================] - 1s 8us/step - loss: 0.8733 - acc: 0.7063 - val_loss: 1.0644 - val_acc: 0.6648
Epoch 6/50
60000/60000 [==============================] - 1s 9us/step - loss: 0.8688 - acc: 0.7076 - val_loss: 1.0546 - val_acc: 0.6674
Epoch 7/50
60000/60000 [==============================] - 1s 8us/step - loss: 0.8645 - acc: 0.7091 - val_loss: 1.0452 - val_acc: 0.67

In [88]:
kr.__version__

'2.2.4'

### Build the Neural Network model with 3 Dense layers with 100,100,10 neurons respectively in each layer. Use cross entropy loss function and singmoid as activation in the hidden layers and softmax as activation function in the output layer. Use sgd optimizer with learning rate 0.03.

In [91]:
#Initialize Sequential model

from keras.layers import Dense
classifier = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
classifier.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Add Dense Layer which provides 100 Outputs after applying softmax
classifier.add(tf.keras.layers.Dense(100, activation='sigmoid'))


## Adding the second hidden layer
classifier.add(tf.keras.layers.Dense(100, activation='sigmoid'))

# Adding the output layer
## Adding the second hidden layer
classifier.add(tf.keras.layers.Dense(10, activation='softmax'))


#Add Dense Layer which provides 10 Outputs after applying softmax
classifier.add(tf.keras.layers.Dense(10, activation='softmax'))

In [93]:
sgd_optimizer2 = tf.keras.optimizers.SGD(lr=0.03)
classifier.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])



## Review model

### Run the model

In [94]:
trainX=train_images
trainY=train_labels
testX=test_images
testY=test_labels

classifier.fit(trainX, trainY, 
          validation_data=(testX, testY), 
          epochs=50,
          batch_size=trainX.shape[0])

Train on 60000 samples, validate on 10000 samples
Epoch 1/50
60000/60000 [==============================] - 2s 34us/step - loss: 2.2974 - acc: 0.1269 - val_loss: 2.2975 - val_acc: 0.1257
Epoch 2/50
60000/60000 [==============================] - 1s 9us/step - loss: 2.2974 - acc: 0.1272 - val_loss: 2.2974 - val_acc: 0.1259
Epoch 3/50
60000/60000 [==============================] - 1s 8us/step - loss: 2.2973 - acc: 0.1273 - val_loss: 2.2973 - val_acc: 0.1262
Epoch 4/50
60000/60000 [==============================] - 1s 9us/step - loss: 2.2972 - acc: 0.1276 - val_loss: 2.2972 - val_acc: 0.1264
Epoch 5/50
60000/60000 [==============================] - 0s 8us/step - loss: 2.2971 - acc: 0.1278 - val_loss: 2.2971 - val_acc: 0.1265
Epoch 6/50
60000/60000 [==============================] - 1s 9us/step - loss: 2.2970 - acc: 0.1279 - val_loss: 2.2971 - val_acc: 0.1267
Epoch 7/50
60000/60000 [==============================] - 0s 8us/step - loss: 2.2969 - acc: 0.1280 - val_loss: 2.2970 - val_acc: 0.12